name: Git Hub CI

on:
  push:
    branches:
      - main

jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
