name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      # Etapa 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Etapa 2: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Etapa 3: Login no GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      # Etapa 4: Construir e enviar imagem Docker
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:main
            ghcr.io/${{ github.repository }}:latest

      # Etapa 5: Configurar credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Etapa 6: Fazer deploy diretamente na EC2
      - name: Deploy on EC2
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --comment "Deploying Docker container" \
            --parameters commands="sudo docker pull ghcr.io/${{ github.repository }}:latest && sudo docker stop meu-app || true && sudo docker rm meu-app || true && sudo docker run -d --name meu-app -p 80:80 ghcr.io/${{ github.repository }}:latest" \
            --output text
