name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      # Etapa 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Etapa 2: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Etapa 3: Login no GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      # Etapa 4: Construir e enviar imagem Docker
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:main
            ghcr.io/${{ github.repository }}:latest

      # Etapa 5: Configurar chave SSH
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Etapa 6: Depurar configuração SSH
      - name: Debug SSH setup
        run: |
          echo "=== Listando arquivos em ~/.ssh ==="
          ls -l ~/.ssh
          echo "=== Conteúdo do arquivo ~/.ssh/known_hosts ==="
          cat ~/.ssh/known_hosts

      # Etapa 7: Testar conexão SSH
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"

      # Etapa 8: Conectar à EC2 e realizar o deploy
      - name: Connect to EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop meu-app || true
            docker rm meu-app || true
            docker run -d --name meu-app -p 80:80 ghcr.io/${{ github.repository }}:latest
          EOF
